export default [
  {
    _id: "201",
    username: "naruto",
    password: "uzumaki123",
    firstName: "Naruto",
    lastName: "Uzumaki",
    email: "naruto@leafvillage.com",
    dob: "October 10, 1997",
    role: "STUDENT",
  },
  {
    _id: "202",
    username: "sasuke",
    password: "uchiha123",
    firstName: "Sasuke",
    lastName: "Uchiha",
    email: "sasuke@leafvillage.com",
    dob: "July 23, 1997",
    role: "STUDENT",
  },
  {
    _id: "203",
    username: "sakura",
    password: "haruno123",
    firstName: "Sakura",
    lastName: "Haruno",
    email: "sakura@leafvillage.com",
    dob: "March 28, 1997",
    role: "STUDENT",
  },
  {
    _id: "204",
    username: "kakashi",
    password: "hatake123",
    firstName: "Kakashi",
    lastName: "Hatake",
    email: "kakashi@leafvillage.com",
    dob: "September 15, 1978",
    role: "STUDENT",
  },
  {
    _id: "205",
    username: "rocklee",
    password: "lee123",
    firstName: "Rock",
    lastName: "Lee",
    email: "rocklee@leafvillage.com",
    dob: "November 27, 1995",
    role: "STUDENT",
  },
  {
    _id: "206",
    username: "neji",
    password: "hyuga123",
    firstName: "Neji",
    lastName: "Hyuga",
    email: "neji@leafvillage.com",
    dob: "July 3, 1995",
    role: "STUDENT",
  },
  {
    _id: "207",
    username: "hinata",
    password: "hyuga123",
    firstName: "Hinata",
    lastName: "Hyuga",
    email: "hinata@leafvillage.com",
    dob: "December 27, 1994",
    role: "STUDENT",
  },
  {
    _id: "208",
    username: "shikamaru",
    password: "nara123",
    firstName: "Shikamaru",
    lastName: "Nara",
    email: "shikamaru@leafvillage.com",
    dob: "September 22, 1995",
    role: "STUDENT",
  },
  {
    _id: "209",
    username: "choji",
    password: "akimichi123",
    firstName: "Choji",
    lastName: "Akimichi",
    email: "choji@leafvillage.com",
    dob: "May 1, 1996",
    role: "STUDENT",
  },
  {
    _id: "210",
    username: "ino",
    password: "yamanaka123",
    firstName: "Ino",
    lastName: "Yamanaka",
    email: "ino@leafvillage.com",
    dob: "September 23, 1996",
    role: "STUDENT",
  },
  {
    _id: "211",
    username: "shino",
    password: "aburame123",
    firstName: "Shino",
    lastName: "Aburame",
    email: "shino@leafvillage.com",
    dob: "January 23, 1996",
    role: "STUDENT",
  },
  {
    _id: "212",
    username: "kiba",
    password: "inuzuka123",
    firstName: "Kiba",
    lastName: "Inuzuka",
    email: "kiba@leafvillage.com",
    dob: "July 7, 1995",
    role: "STUDENT",
  },
  {
    _id: "213",
    username: "tenten",
    password: "tenten123",
    firstName: "Tenten",
    lastName: "",
    email: "tenten@leafvillage.com",
    dob: "March 9, 1996",
    role: "STUDENT",
  },
  {
    _id: "214",
    username: "shizune",
    password: "shizune123",
    firstName: "Shizune",
    lastName: "",
    email: "shizune@leafvillage.com",
    dob: "November 18, 1980",
    role: "STUDENT",
  },
  {
    _id: "215",
    username: "tsunade",
    password: "tsunade123",
    firstName: "Tsunade",
    lastName: "",
    email: "tsunade@leafvillage.com",
    dob: "August 2, 1960",
    role: "STUDENT",
  },
  {
    _id: "216",
    username: "jiraiya",
    password: "jiraiya123",
    firstName: "Jiraiya",
    lastName: "",
    email: "jiraiya@leafvillage.com",
    dob: "November 11, 1960",
    role: "STUDENT",
  },
  {
    _id: "217",
    username: "orochimaru",
    password: "orochimaru123",
    firstName: "Orochimaru",
    lastName: "",
    email: "orochimaru@leafvillage.com",
    dob: "October 27, 1960",
    role: "STUDENT",
  },
  {
    _id: "218",
    username: "hinata",
    password: "hinata123",
    firstName: "Hinata",
    lastName: "Uzumaki",
    email: "hinata@leafvillage.com",
    dob: "December 27, 1994",
    role: "STUDENT",
  },
  {
    _id: "219",
    username: "shikadai",
    password: "nara123",
    firstName: "Shikadai",
    lastName: "Nara",
    email: "shikadai@leafvillage.com",
    dob: "September 22, 2006",
    role: "STUDENT",
  },
  {
    _id: "220",
    username: "boruto",
    password: "uzumaki123",
    firstName: "Boruto",
    lastName: "Uzumaki",
    email: "boruto@leafvillage.com",
    dob: "March 27, 2005",
    role: "STUDENT",
  },
];
